export const ADD_BELEGUNG = "ADD_BELEGUNG";
export const FETCH_BEL_REQUESTED = "FETCH_BEL_REQUEST";
export const FETCH_BEL_FAILURE = "FETCH_BEL_FAILURE";
export const FETCH_BEL_SUCCESS = "FETCH_BEL_SUCCESS";
